### ISSUE TITLE
Sugerencias.

### ISSUE THREAD

**Issue by vidimus** [mmartinez3982/MAD_Map001#1]
Hola, @mmartinez3982 

Lo primero, gracias por el escenario.

Le he echado un vistazo por encima, sólo el comienzo con la intención de jugarlo pronto, y me ha gustado lo que he visto. Es interesante la premisa del escenario.

Me gustaría hacerte un par de sugerencias sobre la portada y el inicio del mismo. Aunque parezca una tontería, añadir una imagen que luego salga en el listado de selección de escenarios y una línea dando una pista de la trama es importante para captar la atención de los jugadores. Del mismo modo, en la pantalla de introducción antes de iniciar el escenario, una imagen sugerente y una descripción atractiva ayuda bastante. Que el futuro jugador/es se enganche a ese adelanto y quiera conocer el resto de la historia. Indicar el tipo de escenario (acción, deducción, si hace falta tomar notas, número de jugadores, etc.) también es un detalle que se agradece.

Cuando juegue el escenario te daré mi opinión rellenando el formulario que hay al final.

Un saludo.

**Comment by mmartinez3982** [comment]
Hola @vidimus ,

Gracias a vosotros por crear una herramienta que permita crear cualquier tipo de partida; es genial y amplía mucho el juego. Y en especial gracias a tí por darle un vistazo.

Tomo nota de tus sugerencias. Estos días sacaré tiempo para configurar lo que me comentas para que sea más atractivo a quien lo vea. Este fin de semana jugaremos dos personas el escenario y me anotaré fallos y posibles mejoras que hacerle. Tengo ganas de probar qué tal resulta y afinar y ajustarlo para dejarlo lo más atractivo posible.

¡Saludos y gracias!

**Comment by mmartinez3982** [comment]
Hola @vidimus ,

He agregado un icono y cambiado algo la descripción. También he realizado una serie de cambios en el comienzo y final de la partida; ahora es más "agradable" de ver. También he realizado una serie de cambios menores.

Gracias por la sugerencia.
Un saludo.
